FROM python:3.11-slim

WORKDIR /mlflow/

RUN pip install --no-cache-dir mlflow==2.10.2


# Build Docker image:
# docker build -t "name_image" .

# Chạy container:
# docker run -d -p 8000:8000 "name_image"

# Dừng container:
# docker stop fastapi-demo < or id container> 

# Check Docker imges:
# docker images
    
# Check Docker Container:
# docker ps
# docker ps -a

# Xóa Docker Container:
# docker rm [CONTAINER ID]

# Xóa Docker Images:
# docker rmi [IMAGE ID]